id = "codemate"
name = "codemate"
description = "The open source coding agent."
version = "1.14.48"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/codemate"

[agent_servers.codemate]
name = "codemate"
icon = "./icons/codemate.svg"

[agent_servers.codemate.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/codemate/releases/download/v1.14.48/codemate-darwin-arm64.zip"
cmd = "./codemate"
args = ["acp"]

[agent_servers.codemate.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/codemate/releases/download/v1.14.48/codemate-darwin-x64.zip"
cmd = "./codemate"
args = ["acp"]

[agent_servers.codemate.targets.linux-aarch64]
archive = "https://github.com/anomalyco/codemate/releases/download/v1.14.48/codemate-linux-arm64.tar.gz"
cmd = "./codemate"
args = ["acp"]

[agent_servers.codemate.targets.linux-x86_64]
archive = "https://github.com/anomalyco/codemate/releases/download/v1.14.48/codemate-linux-x64.tar.gz"
cmd = "./codemate"
args = ["acp"]

[agent_servers.codemate.targets.windows-x86_64]
archive = "https://github.com/anomalyco/codemate/releases/download/v1.14.48/codemate-windows-x64.zip"
cmd = "./codemate.exe"
args = ["acp"]
