import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const CODEMATE_EXPERIMENTAL = truthy("CODEMATE_EXPERIMENTAL")
const CODEMATE_DISABLE_CLAUDE_CODE = truthy("CODEMATE_DISABLE_CLAUDE_CODE")
const CODEMATE_DISABLE_CLAUDE_CODE_SKILLS =
  CODEMATE_DISABLE_CLAUDE_CODE || truthy("CODEMATE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["CODEMATE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  CODEMATE_AUTO_SHARE: truthy("CODEMATE_AUTO_SHARE"),
  CODEMATE_AUTO_HEAP_SNAPSHOT: truthy("CODEMATE_AUTO_HEAP_SNAPSHOT"),
  CODEMATE_GIT_BASH_PATH: process.env["CODEMATE_GIT_BASH_PATH"],
  CODEMATE_CONFIG: process.env["CODEMATE_CONFIG"],
  CODEMATE_CONFIG_CONTENT: process.env["CODEMATE_CONFIG_CONTENT"],
  CODEMATE_DISABLE_AUTOUPDATE: truthy("CODEMATE_DISABLE_AUTOUPDATE"),
  CODEMATE_ALWAYS_NOTIFY_UPDATE: truthy("CODEMATE_ALWAYS_NOTIFY_UPDATE"),
  CODEMATE_DISABLE_PRUNE: truthy("CODEMATE_DISABLE_PRUNE"),
  CODEMATE_DISABLE_TERMINAL_TITLE: truthy("CODEMATE_DISABLE_TERMINAL_TITLE"),
  CODEMATE_SHOW_TTFD: truthy("CODEMATE_SHOW_TTFD"),
  CODEMATE_PERMISSION: process.env["CODEMATE_PERMISSION"],
  CODEMATE_DISABLE_DEFAULT_PLUGINS: truthy("CODEMATE_DISABLE_DEFAULT_PLUGINS"),
  CODEMATE_DISABLE_LSP_DOWNLOAD: truthy("CODEMATE_DISABLE_LSP_DOWNLOAD"),
  CODEMATE_ENABLE_EXPERIMENTAL_MODELS: truthy("CODEMATE_ENABLE_EXPERIMENTAL_MODELS"),
  CODEMATE_DISABLE_AUTOCOMPACT: truthy("CODEMATE_DISABLE_AUTOCOMPACT"),
  CODEMATE_DISABLE_MODELS_FETCH: truthy("CODEMATE_DISABLE_MODELS_FETCH"),
  CODEMATE_DISABLE_MOUSE: truthy("CODEMATE_DISABLE_MOUSE"),
  CODEMATE_DISABLE_CLAUDE_CODE,
  CODEMATE_DISABLE_CLAUDE_CODE_PROMPT: CODEMATE_DISABLE_CLAUDE_CODE || truthy("CODEMATE_DISABLE_CLAUDE_CODE_PROMPT"),
  CODEMATE_DISABLE_CLAUDE_CODE_SKILLS,
  CODEMATE_DISABLE_EXTERNAL_SKILLS: truthy("CODEMATE_DISABLE_EXTERNAL_SKILLS"),
  CODEMATE_FAKE_VCS: process.env["CODEMATE_FAKE_VCS"],
  CODEMATE_SERVER_PASSWORD: process.env["CODEMATE_SERVER_PASSWORD"],
  CODEMATE_SERVER_USERNAME: process.env["CODEMATE_SERVER_USERNAME"],
  CODEMATE_ENABLE_QUESTION_TOOL: truthy("CODEMATE_ENABLE_QUESTION_TOOL"),

  // Experimental
  CODEMATE_EXPERIMENTAL,
  CODEMATE_EXPERIMENTAL_FILEWATCHER: Config.boolean("CODEMATE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CODEMATE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("CODEMATE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CODEMATE_EXPERIMENTAL_ICON_DISCOVERY: CODEMATE_EXPERIMENTAL || truthy("CODEMATE_EXPERIMENTAL_ICON_DISCOVERY"),
  CODEMATE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("CODEMATE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  CODEMATE_ENABLE_EXA: truthy("CODEMATE_ENABLE_EXA") || CODEMATE_EXPERIMENTAL || truthy("CODEMATE_EXPERIMENTAL_EXA"),
  CODEMATE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("CODEMATE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  CODEMATE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("CODEMATE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  CODEMATE_EXPERIMENTAL_OXFMT: CODEMATE_EXPERIMENTAL || truthy("CODEMATE_EXPERIMENTAL_OXFMT"),
  CODEMATE_EXPERIMENTAL_LSP_TY: truthy("CODEMATE_EXPERIMENTAL_LSP_TY"),
  CODEMATE_EXPERIMENTAL_LSP_TOOL: CODEMATE_EXPERIMENTAL || truthy("CODEMATE_EXPERIMENTAL_LSP_TOOL"),
  CODEMATE_EXPERIMENTAL_PLAN_MODE: CODEMATE_EXPERIMENTAL || truthy("CODEMATE_EXPERIMENTAL_PLAN_MODE"),
  CODEMATE_EXPERIMENTAL_MARKDOWN: !falsy("CODEMATE_EXPERIMENTAL_MARKDOWN"),
  CODEMATE_MODELS_URL: process.env["CODEMATE_MODELS_URL"],
  CODEMATE_MODELS_PATH: process.env["CODEMATE_MODELS_PATH"],
  CODEMATE_DISABLE_EMBEDDED_WEB_UI: truthy("CODEMATE_DISABLE_EMBEDDED_WEB_UI"),
  CODEMATE_DB: process.env["CODEMATE_DB"],
  CODEMATE_DISABLE_CHANNEL_DB: truthy("CODEMATE_DISABLE_CHANNEL_DB"),
  CODEMATE_SKIP_MIGRATIONS: truthy("CODEMATE_SKIP_MIGRATIONS"),
  CODEMATE_STRICT_CONFIG_DEPS: truthy("CODEMATE_STRICT_CONFIG_DEPS"),

  CODEMATE_WORKSPACE_ID: process.env["CODEMATE_WORKSPACE_ID"],
  CODEMATE_EXPERIMENTAL_HTTPAPI: truthy("CODEMATE_EXPERIMENTAL_HTTPAPI"),
  CODEMATE_EXPERIMENTAL_WORKSPACES: CODEMATE_EXPERIMENTAL || truthy("CODEMATE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get CODEMATE_DISABLE_PROJECT_CONFIG() {
    return truthy("CODEMATE_DISABLE_PROJECT_CONFIG")
  },
  get CODEMATE_TUI_CONFIG() {
    return process.env["CODEMATE_TUI_CONFIG"]
  },
  get CODEMATE_CONFIG_DIR() {
    return process.env["CODEMATE_CONFIG_DIR"]
  },
  get CODEMATE_PURE() {
    return truthy("CODEMATE_PURE")
  },
  get CODEMATE_PLUGIN_META_FILE() {
    return process.env["CODEMATE_PLUGIN_META_FILE"]
  },
  get CODEMATE_CLIENT() {
    return process.env["CODEMATE_CLIENT"] ?? "cli"
  },
}
